import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'kwon Test',
  description: 'Generated by it`s me',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel='manifest' href='/manifest.json' />
        <link rel='apple-touch-icon' href='/icon-192x192.png'></link>
        <meta name='theme-color' content='#84A59D' />
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
